import Head from "next/head";
import {
  AiFillGithub,
  AiFillLinkedin,
  AiFillCode,
  AiFillYoutube,
  AiTwotoneMail,
} from "react-icons/ai";

import {
  SiLua,
  SiHtml5,
  SiJavascript,
  SiMinecraft,
  SiCss3,
  SiAdobe,
  SiOpenai,
  SiOracle,
  SiNextdotjs,
  SiJson,
  SiCsswizardry,
  SiTypescript,
  SiTailwindcss,
  SiReact,
} from "react-icons/si"
import React, { useState } from 'react';
import { Name } from './name.tsx' 
import { motion } from "framer-motion"


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Zack Darnell Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Zack Darnell</h1>
            <ul className="flex items-center">
              <li>
      <label className="toggleDarkBtn flex md:mx-12 md:-my-2 -my-2 -mx-20" >
        <input type="checkbox" onClick={() => setDarkMode(!darkMode)} />
        <span className="slideBtnTg round"></span>
      </label>
              </li>
              <li>
                <a
                  className="dark:bg-info dark:text-black bg-gradient-to-r from-purple-500 font-bold to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://doc-04-8g-docs.googleusercontent.com/docs/securesc/uk5lhot1lomkv4umut57qrjpcf0bvlp5/tbufr351na0snjvk7pa9aeer9dlgblo1/1673994075000/12703160565844601407/11296394643127616404/1Z55SFBt9YXsrTudy7W-xDrLElxtuopfV?e=download&ax=ALjR8symUPR4mIEqiiodEM4YH0tLXvzmrXgqPcm9bD53GBN3OhwJFn3irNwtm-vweY6wcGjkjzHrjpPlQ4ydTlasKz3tPEseKm-ypJpyPjRE_XfjLBvjt77uUKgn2QL0llduENhdMmcihbhFhefF_E0o86PsSesMcr3qsat7GkmsSCEvd8dPAMWkp_M4aWdMGdUgTEnp_MupMpu9YJfwD93ckrQ-nBII9cGs6KV3MOSQjR_Jp8rMl0842IN6mv1HXKBP_wn_oLIgZcN7IhZhAjboycR9DHv32XHBzLYIqolsT7tQGttNQBrpaJDTUjAJMLC7Mu_zwCnwxSsjs3nKPagRvJCSy0atinjzmsE1k9QC6utfQSnDSHoPUNMiN4ZRDFBulCLJb2xa5JRQqmvYSGFbKXzDCNLgJUolW4MzAuIy4WDmJOb_f6hBL_jOaVCn1YE50a5KEDKVPZOk_j73olwbD5DgRMgOwadWVC_16es3j8RzmN8N0517ikdSLjkQ3KmFPlUUFDA6XsHqD6gKEoO-Eyf7JRrKzy_NlbWBDjLAm8CXSA9R8GMSzsnp9n67G9TiqDSWT2DAmt4EgiqZ8U0E-3sJvYIcRsh_BpcyTlRVDX-aSN1daDD_ARDcjRw7IjWc_iJUg9vB7rpNO61FZGPTHRzifuinRS4nh7xwm9akmH_yQb9dYCoblOmZXay6r1WdITOL3A5njuY4-mUMgbY2wPIrLTacICArMCZS-ivX8TDEUXytS7AMWMotDr-Nvc2XFFtp63jovmjmZ-SWy7iovc7muojjXcsQ1C69yk6fQLqx9RCFGxW121K7MGuO4YGDruJ_ltpmsEQ9nKQMfFMvZ5HFfIDiL57fpb2vHyXhY6pkk3kaHY1DCSsjfikohJ0gKR706_qg-u8cHeazmIUYg3pqAc2pOUCQsL8s3nIE9OslJH1V3y70F7KWneE0sIBA95YH7onq&uuid=400d84bc-b8dd-4a55-8726-5e3f183a9627&authuser=0&nonce=guen89tjt8ppo&user=11296394643127616404&hash=87ncjcsnmcnvjde573n16s5vm8ef4im3">
                  Resume
                </a>
              </li>
            </ul>
          </nav>
        <motion.div 
                  initial={{
                    y: -500,
                    opacity: 0,
                    scale: 0.5
                  }}
                  animate={{
                    y: 0,
                    opacity: 1,
                    scale: 1
                  }}
                  transition={{
                    duration: 2
                  }}
        className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 dark:text-teal-500 md:text-6xl font-bold">
              Zack Darnell
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Developer and designer.
            </h3>

            <div className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            <Name >
            </Name>
            </div>

            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a className="hover:rotate-6 hover:scale-125 ease-in-out transition duration-700" href="">
              <AiFillGithub />
              </a>
              <a className="hover:-rotate-6 hover:scale-125 ease-in-out transition duration-700" href="https://www.linkedin.com/in/zack-darnell-837596201/">
              <AiFillLinkedin />
              </a>
              <a className="hover:rotate-6 hover:scale-125  ease-in-out transition duration-700" href="https://www.youtube.com/@ZACKDEV/featured">
              <AiFillYoutube />
              </a>
              <a className="hover:-rotate-6 hover:scale-125  ease-in-out transition duration-700" href="mailto:zackddesigns@outlook.com">
                <AiTwotoneMail />
              </a>
            </div>
            <div>
            <img
            className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-48 h-48 relative overflow-hidden mt-15 md:h-46 md:w-46"
            src="https://media.licdn.com/dms/image/C4E03AQH-eKzrOmfbFA/profile-displayphoto-shrink_200_200/0/1607796406609?e=1678924800&v=beta&t=YvoVqrlgRSYVgKZ0IWPHZoZa0NR8X4ONNVwQc1yqq5A"
            />
            </div>
        </motion.div>
        </section>
        
        <section>
          <div className="my-1">
            <h3 className="text-3xl font-bold py-1 dark:text-white ">ABOUT ME</h3>
            <p className="text-md py-1 leading-8 text-gray-800 dark:text-gray-200 font-serif">
              When I started it was awhile back coding within Minecraft, which advanced to learning new things
              making new projects and working together with others. I eventually used those skills again at Quick Quack
              which I had made a gift-card generator program using HTML, CSS, and JavaScript. After then
              <span className="text-teal-500 font-bold font-serif"> freelancing </span>
              became a hobby of mine! Currently looking to get <span className="font-serif font-bold text-teal-500">hired </span>
              and collaborate with talanted people to create digital products
              for both business and consumer use.
            </p>
          </div>
          <p className="text-3xl py-2 leading-8 text-gray-800 font-bold dark:text-gray-200">
              PROJECTS!
            </p>
          <div className="lg:flex gap-10 -my-4 -py-20">
            <div className="text-center shadow-xl p-4 rounded-md  my-10 bg-gradient-to-b from-teal-600 to-white  dark:bg-info flex-1">
              <h3 className="text-xl font-bold pt-8 pb-2  ">
                FiveM Pause Menu
              </h3>
              <p className="py-2 font-serif">
                Created an elegant pause menu for fivem game which is GTA Online version
                for roleplaying in the game. Using the natives for Lua Scripting from fivem I curated an eye-popping
                pause menu with seemless animations!
              </p>
              <a
              className=""
               href="https://github.com/ZeroScriptz/zPause">
              <button 
                
                className="hover:scale-105 hover:opacity-75 shadow-xl ease-in-out duration-700 hover:rotate-6 bg-gradient-to-tr from-teal-700 opacity-60  to-white backdrop-blur-xl dark:bg-info px-1 py-1 border-none rounded-md ml-2  "
                >
                  <h1 className="text-sm font-bold font-serif text-bold  text-black">
                  Source
                  </h1> 
                  </button>
                    </a>
                  <text className="px-1">●</text>
                  <a href="https://github.com/ZeroScriptz/zPause/releases/tag/v1.0.0">
                  <button 
                href="/"
                className="shadow-xl bg-gradient-to-tl ease-in-out duration-700 from-teal-700 opacity-60 hover:scale-105 hover:-rotate-6  hover:opacity-75 to-white dark:bg-info text-sm font-bold font-serif text-black px-1 py-1 border-none rounded-md ml-2"
                >
                  Download
                  </button>
                  </a>
              <h4 className="py-4 text-black font-bold">Languages Used</h4>
              <div className="text-5xl flex justify-center my-30 text-gray-600 dark:text-gray-400">
              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiLua className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiHtml5 className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiJavascript className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiCsswizardry className=" text-5xl" /></p>
              </div>
            </div>
            <div className=" text-center shadow-xl p-10 rounded-md my-10 bg-gradient-to-b  from-teal-600 to-white  dark:bg-info flex-1">

              <h3 className="text-lg font-bold pt-8 pb-2 ">
                M4A : Music 4 All 
              </h3>
              <p className="py-2 font-serif">
                Using tailwind, shazam-core API, react, and more. Creating API endpoints for top charts,
                artist, related songs, and others. Shows top artist, top songs, related artists, and more!
                This provides a seemless UI/UX for users along with low cpu usage rates. 
              </p>
              <a href="https://github.com/ZeroScriptz/music4all">
              <button 
                
                className="shadow-xl bg-gradient-to-tr from-teal-700 opacity-60 hover:scale-105 hover:opacity-75 to-white dark:bg-info  text-sm font-bold font-serif text-bold  text-black px-1 py-1 border-none rounded-md ml-2"
                >
                  Source 
                  </button>
                  </a>
                  <text className="px-1">●</text>
                  <a href="https://musicforall.netlify.app">
                  <button 
                
                className="shadow-xl bg-gradient-to-tl  from-teal-700 opacity-60 hover:scale-105 hover:opacity-75 to-white dark:bg-info text-sm font-bold font-serif text-bold  text-black px-1 py-1 border-none rounded-md ml-2"
                >
                  LIVE VIEW
                  </button>
                  </a>
              <h4 className="py-4 pb-2 font-bold text-black">Design Tools I Use</h4>
              <div className="text-5xl flex justify-center my-30 text-gray-600 dark:text-gray-400">
              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiReact className=" text-5xl" /></p>
              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiTailwindcss className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiHtml5 className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiJavascript className=" text-5xl" /></p>
              </div>
            </div>
            <div className="text-center  p-10 rounded-md my-10 shadow-xl bg-gradient-to-b from-teal-600 to-white dark:bg-info flex-1">
              <h3 className="text-lg font-bold pt-8 pb-2 ">Code-Eye AI</h3>
              <p className="py-2 font-serif">
              A lot of people LOVE ChatGPT, though anyone notice that it is hard to access due to EVERYONE using it? 
              Well I created a Web Application using HTML, CSS, JavaScript and the OpenAI API to never worry about the wait time on ChatGPT !
              </p>
              <a href="https://github.com/ZeroScriptz/code-eye-ai">
              <button 
                
                className="shadow-xl bg-gradient-to-tr from-teal-700 opacity-60 hover:scale-105 hover:opacity-75 to-white dark:bg-info  text-sm font-bold font-serif text-bold  text-black px-1 py-1 border-none rounded-md ml-2"
                >
                  Source 
                  </button>
                  </a>
                  <text className="px-1">●</text>
                  <a href="https://code-eye.vercel.app">
                  <button 
                
                className="shadow-xl bg-gradient-to-tl  from-teal-700 opacity-60 hover:scale-105 hover:opacity-75 to-white dark:bg-info text-sm font-bold font-serif text-bold  text-black px-1 py-1 border-none rounded-md ml-2"
                >
                  LIVE VIEW
                  </button>
                  </a>
              <h4 className="py-4 text-black font-bold">Design Tools I Use</h4>
              <div className="text-5xl flex justify-center my-30 text-gray-600 dark:text-gray-400">
              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiHtml5 className=" text-5xl" /></p>
              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiOpenai className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiCss3 className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiJavascript className=" text-5xl" /></p>
              </div>
            </div>
          </div>
        </section>
        <section className="py-10">
          <section>
          <div className="my-1">
            <p className="text-3xl my-10 leading-8 text-gray-800 font-bold dark:text-gray-200">
              YouTube!
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-xl p-10 rounded-md hover:-my-2 ease-in-out duration-700  my-10 bg-gradient-to-b from-teal-600 to-white  dark:bg-info flex-1">
              <h3 className="text-xl font-bold pt-8 pb-2  ">
                Make Furniture in Minecraft!
              </h3>
              <a
              href="https://www.youtube.com/watch?v=ch4Fufti5Rg&t=0s"
              >
              <img
              
              src="https://img.youtube.com/vi/ch4Fufti5Rg/maxresdefault.jpg"
              className="shadow-xl rounded-md hover:scale-105 transition duration-500 ease-in-out "
              />
              </a>
              <p className="py-2 font-serif">
              Learn to create stunning custom objects in Minecraft by using BlockBench for modeling and the Oraxen plugin for functionality, 
              all without the need for a modpack. Utilize YAML/YML configuration to easily add a variety of cool objects, plants, and more to your Minecraft world.
              </p>

              <h4 className="py-4 text-black font-bold">Design Tools Used</h4>

              <div className="text-xl flex justify-center my-30 text-gray-600 dark:text-gray-400">

              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiMinecraft className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiAdobe className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><AiFillCode className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiJson className=" text-5xl" /></p>
              </div>
            </div>
            <div className=" text-center shadow-xl p-10 rounded-md my-10 bg-gradient-to-b hover:-my-2 ease-in-out duration-700  from-teal-600 to-white  dark:bg-info flex-1">

              <h3 className="text-lg font-bold pt-8 pb-2 ">
                Develope free Servers using Oracle
              </h3>
              <a href="https://www.youtube.com/watch?v=nJb12LbktVk&t=0s">
                <img 
                className="shadow-xl rounded-md hover:scale-105 transition duration-500 ease-in-out"
                src="https://img.youtube.com/vi/nJb12LbktVk/maxresdefault.jpg"
                />
              </a>
              <p className="py-2 font-serif">
              Learn how to use Termius, Ubuntu, SFTP, Linux commands, edit files within the terminal, and set up 
              ingress rules for port forwarding for UDP/TCP using the Always Free tier of Oracle Cloud Service. 
              This tutorial will guide users through the process in an easy to follow manner.
              </p>
              <h4 className="py-4 pb-2 font-bold text-black">Design Tools I Use</h4>
              <div className="text-5xl flex justify-center my-30 text-gray-600 dark:text-gray-400">
              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiMinecraft className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiAdobe className="text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><AiFillCode className="text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiJson className="text-5xl" /></p>
              </div>
            </div>
            <div className="text-center shadow-xl p-10 rounded-md hover:-my-2 ease-in-out duration-700  my-10 bg-gradient-to-b from-teal-600 to-white dark:bg-info flex-1">
              <h3 className="text-lg font-bold pt-8 pb-2 ">Make consumable items in Minecraft! </h3>
              <a href="https://www.youtube.com/watch?v=kjN9uPcu3hc&t=0s">
                <img 
                className="shadow-xl rounded-md hover:scale-105 transition duration-500 ease-in-out"
                src="https://img.youtube.com/vi/kjN9uPcu3hc/maxresdefault.jpg"
                />
              </a>
              <p className="py-2 font-serif">
              Unlock the potential to create one-of-a-kind consumable items in Minecraft by using skin editing software such as Photoshop and configuring using YML/YAML in Oraxen. 
              Enhance your Minecraft experience with custom consumable items that offer unique effects and more.
              </p>

              <h4 className="py-4 text-black font-bold">Design Tools I Use</h4>
              <div className="text-5xl flex justify-center my-30 text-gray-600 dark:text-gray-400">
              <p className="text-gray-800 pb-2 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><SiMinecraft className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiAdobe className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:-rotate-12 ease-in-out duration-700"><AiFillCode className=" text-5xl" /></p>
              <p className="text-gray-800 py-2 px-3 hover:scale-105 hover:rotate-12 ease-in-out duration-700"><SiOracle className=" text-5xl" /></p>
              </div>
            </div>
          </div>
        </section>
        <section>
        <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            Starting out with my portfolio I was
              developing in minecraft for awhile but never
              did any good documentation. Furthermore I made
              my youtube that went great and did work on smaller projects. Later more I worked for
               Quick Quack made the gift-card generator program then continued to learn! Later on I made some FiveM Game scripts and 
              <span className="text-teal-500"> sold </span>
              those assets completely. Later on I continued my growth with  <span className="text-teal-500"> Coursera </span>
              courses and have made a few projects from what I have learned along with continuing to make more! 
              Whether its Ai Generation or something new I am always willing to learn.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I do offer a range of services from Web Development, Front End Development, Shopify Development, Brand Design and more!
              Contact me through LinkedIn or the Email Button above.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
            </div>
            <div className="basis-1/3 flex-1">

            </div>
            <div className="basis-1/3 flex-1">

            </div>
            <div className="basis-1/3 flex-1">

            </div>
            <div className="basis-1/3 flex-1">
            
            </div>
            
            <div className="basis-1/3 flex-1">

            </div>
          
          </div>
        </section>
        </section>
      </main>
      <div>
      
        </div>

    </div>
  );
}
